version: '3'
services:
  app:
    image: iais.meta:latest
    ports:
      - 8080:8200
    environment:
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres?currentSchema=iais_meta
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=iais_meta
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
    depends_on:
      - db
    build: .  
  db:
    image: iais.db.meta:latest
    ports:
    - "5432:5432"
    build:
     context: .
     dockerfile: db.Dockerfile
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

